google.maps.__gjsload__('geometry', function(_){var eqa=function(a,b){return Math.abs(_.tm(b-a,-180,180))},fqa=function(a,b,c,d,e){if(!d){c=eqa(a.lng(),c)/eqa(a.lng(),b.lng());if(!e)return e=Math.sin(_.vl(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.vl(b.lat())),_.wl(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.Jo(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.vl(a.lat());a=_.vl(a.lng());d=_.vl(b.lat());b=_.vl(b.lng());c=_.vl(c);return _.tm(_.wl(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},gqa=function(a,b){a=new _.pn(a,!1);b=new _.pn(b,!1);return a.equals(b)},hqa=function(a,b,c){a=_.vn(a);c=c||1E-9;const d=_.tm(a.lng(),-180,180),e=b instanceof _.fu,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(let r=0,t=g.getLength();r<t;++r){const v=g.getAt(r),w=v.getLength(),y=e?w:w-1;for(let E=0;E<y;++E){var h=v.getAt(E);const H=v.getAt((E+
1)%w);if(gqa(h,a)||gqa(H,a))return!0;var k=_.tm(h.lng(),-180,180),n=_.tm(H.lng(),-180,180);const M=Math.max(k,n),I=Math.min(k,n);if(k=Math.abs(_.tm(k-n,-180,180))<=1E-9&&(Math.abs(_.tm(k-d,-180,180))<=c||Math.abs(_.tm(n-d,-180,180))<=c)){k=a.lat();n=Math.min(h.lat(),H.lat())-c;var p=Math.max(h.lat(),H.lat())+c;k=k>=n&&k<=p}if(k)return!0;if(M-I>180?d+c>=M||d-c<=I:d+c>=I&&d-c<=M)if(h=fqa(h,H,d,f,b),Math.abs(h-a.lat())<c)return!0}}return!1},iqa=function(a,b){const c=_.rn(a);a=_.sn(a);const d=_.rn(b);
b=_.sn(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))},jqa=function(a,b,c){a=_.vn(a);b=_.vn(b);c=c||6378137;return iqa(a,b)*c},mqa=function(a,b){b=b||6378137;a instanceof _.xp&&(a=a.getArray());a=(0,_.Ws)(a);if(a.length===0)return 0;const c=Array(4),d=Array(3),e=[1,0,0,0],f=Array(3);kqa(a[a.length-1],f);for(let v=0;v<a.length;++v)kqa(a[v],d),FC(f,d,c),lqa(c,e,e),[f[0],f[1],f[2]]=d;const [g,h,k]=f,[n,p,r,t]=e;return 2*Math.atan2(g*
p+h*r+k*t,n)*(b*b)},nqa=function(a,b){if(isFinite(a)){var c=a%360;a=Math.round(c/90);c-=a*90;if(c===30||c===-30){c=Math.sign(c)*.5;var d=Math.sqrt(.75)}else c===45||c===-45?(c=Math.sign(c)*Math.SQRT1_2,d=Math.SQRT1_2):(d=c/180*Math.PI,c=Math.sin(d),d=Math.cos(d));switch(a&3){case 0:b[0]=c;b[1]=d;break;case 1:b[0]=d;b[1]=-c;break;case 2:b[0]=-c;b[1]=-d;break;default:b[0]=-d,b[1]=c}}else b[0]=NaN,b[1]=NaN},kqa=function(a,b){const c=Array(2);nqa(a.lat(),c);const [d,e]=c;nqa(a.lng(),c);const [f,g]=c;
b[0]=e*g;b[1]=e*f;b[2]=d},lqa=function(a,b,c){const d=a[0]*b[1]+a[1]*b[0]+a[2]*b[3]-a[3]*b[2],e=a[0]*b[2]-a[1]*b[3]+a[2]*b[0]+a[3]*b[1],f=a[0]*b[3]+a[1]*b[2]-a[2]*b[1]+a[3]*b[0];c[0]=a[0]*b[0]-a[1]*b[1]-a[2]*b[2]-a[3]*b[3];c[1]=d;c[2]=e;c[3]=f},FC=function(a,b,c){var d=a[0]-b[0],e=a[1]-b[1],f=a[2]-b[2];const g=a[0]+b[0],h=a[1]+b[1],k=a[2]+b[2];var n=g*g+h*h+k*k,p=e*k-f*h;f=f*g-d*k;d=d*h-e*g;e=n*n+p*p+f*f+d*d;if(e!==0)b=Math.sqrt(e),c[0]=n/b,c[1]=p/b,c[2]=f/b,c[3]=d/b;else{a:for(n=[a[0]-b[0],a[1]-
b[1],a[2]-b[2]],p=0;p<3;++p)if(n[p]!==0){if(n[p]<0){n=[-n[0],-n[1],-n[2]];break a}break}p=0;for(f=1;f<n.length;++f)Math.abs(n[f])<Math.abs(n[p])&&(p=f);f=[0,0,0];f[p]=1;n=[n[1]*f[2]-n[2]*f[1],n[2]*f[0]-n[0]*f[2],n[0]*f[1]-n[1]*f[0]];p=Math.hypot(...n);n=[n[0]/p,n[1]/p,n[2]/p];p=Array(4);FC(a,n,p);a=Array(4);FC(n,b,a);lqa(a,p,c)}},GC=class{};GC.isLocationOnEdge=hqa;
GC.containsLocation=function(a,b){a=_.vn(a);const c=_.tm(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs");var f=b.get("map");f=!d&&f?f.getProjection():null;let g=!1;for(let k=0,n=e.getLength();k<n;++k){const p=e.getAt(k);for(let r=0,t=p.getLength();r<t;++r){const v=p.getAt(r),w=p.getAt((r+1)%t);var h=_.tm(v.lng(),-180,180);const y=_.tm(w.lng(),-180,180),E=Math.max(h,y);h=Math.min(h,y);(E-h>180?c>=E||c<h:c<E&&c>=h)&&fqa(v,w,c,d,f)<a.lat()&&(g=!g)}}return g||hqa(a,b)};var HC=class{};HC.computeSignedArea=mqa;
HC.computeArea=function(a,b){if(!(a instanceof _.xp||Array.isArray(a)||a instanceof _.wo||a instanceof _.Ap))try{a=_.vo(a)}catch(c){try{a=new _.Ap((0,_.Rea)(a))}catch(d){throw _.Rm("Invalid path passed to computeArea(): "+JSON.stringify(a));}}b=b||6378137;if(a instanceof _.Ap){if(a.getRadius()===void 0)throw _.Rm("Invalid path passed to computeArea(): Circle is missing radius.");if(a.getRadius()<0)throw _.Rm("Invalid path passed to computeArea(): Circle must have non-negative radius.");if(b<0)throw _.Rm("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");
if(a.getRadius()>Math.PI*b)throw _.Rm("Invalid path passed to computeArea(): Circle must not cover more than 100% of the sphere.");return 2*Math.PI*b**2*(1-Math.cos(a.getRadius()/b))}if(a instanceof _.wo){if(b<0)throw _.Rm("Invalid radiusOfSphere passed to computeArea(): radiusOfSphere must be non-negative.");if(a.bj.lo>a.bj.hi)throw _.Rm("Invalid path passed to computeArea(): the southern LatLng of a LatLngBounds cannot be more north than the northern LatLng.");let c=2*Math.PI*b**2*(1-Math.cos((a.bj.lo-
90)*Math.PI/180));c-=2*Math.PI*b**2*(1-Math.cos((a.bj.hi-90)*Math.PI/180));return c*Math.abs(a.xi.hi-a.xi.lo)/360}return Math.abs(mqa(a,b))};HC.computeLength=function(a,b){b=b||6378137;let c=0;a instanceof _.xp&&(a=a.getArray());for(let d=0,e=a.length-1;d<e;++d)c+=jqa(a[d],a[d+1],b);return c};HC.computeDistanceBetween=jqa;HC.traversePath=function(){throw Error("traversePath() is not available in this version of the Maps JavaScript API.");};
HC.interpolate=function(a,b,c){a=_.vn(a);b=_.vn(b);const d=_.rn(a);var e=_.sn(a);const f=_.rn(b),g=_.sn(b),h=Math.cos(d),k=Math.cos(f);b=iqa(a,b);const n=Math.sin(b);if(n<1E-6)return new _.pn(a.lat(),a.lng());a=Math.sin((1-c)*b)/n;c=Math.sin(c*b)/n;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.pn(_.wl(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.wl(Math.atan2(e,b)))};
HC.computeOffsetOrigin=function(a,b,c,d){a=_.vn(a);c=_.vl(c);b/=d||6378137;d=Math.cos(b);const e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.rn(a));const f=e*e*d*d+d*d*d*d-d*d*c*c;if(f<0)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;const h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.sn(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.pn(_.wl(g),_.wl(a))};
HC.computeOffset=function(a,b,c,d){a=_.vn(a);b/=d||6378137;c=_.vl(c);var e=_.rn(a);a=_.sn(a);d=Math.cos(b);b=Math.sin(b);const f=Math.sin(e);e=Math.cos(e);const g=d*f+b*e*Math.cos(c);return new _.pn(_.wl(Math.asin(g)),_.wl(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};HC.computeHeading=function(a,b){a=_.vn(a);b=_.vn(b);const c=_.rn(a),d=_.sn(a);a=_.rn(b);b=_.sn(b)-d;return _.tm(_.wl(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)};var oqa={encoding:_.Iu,spherical:HC,poly:GC};_.za.google.maps.geometry=oqa;_.Sl("geometry",oqa);});
